//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public int idauth { get; set; }
        public string Name { get; set; }
        public string Sername { get; set; }
        public string Login { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> idrole { get; set; }
    
        public virtual role role { get; set; }
    }
}
